2021-10-17 07:38:00,790 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:40:10,961 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:43:22,032 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:44:12,940 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:46:35,950 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:56:11,077 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 07:56:12,312 ERROR: Exception on /manage_cars [GET] [in i:\anaconda\envs\cash\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "i:\anaconda\envs\cash\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\main\routes.py", line 748, in manage_cars
    return render_template('cars.html', cars=cars, personal=False)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\cars.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 117, in block 'content'
    {% block app_content %}{% endblock %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\cars.html", line 14, in block 'app_content'
    {% include '_car_info.html' %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\_car_info.html", line 18, in top-level template code
    <td><a href="{{ url_for('edit_car', car_id=car.id) }}">Edit this car</a></td>
  File "i:\anaconda\envs\cash\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "i:\anaconda\envs\cash\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_car' with values ['car_id']. Did you mean 'main.edit_car' instead?
2021-10-17 07:56:22,998 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 16:05:00,876 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 19:31:47,813 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-10-17 19:31:58,863 ERROR: Exception on /race_info/8 [GET] [in i:\anaconda\envs\cash\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "i:\anaconda\envs\cash\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\main\routes.py", line 947, in race_info
    return render_template('race_info.html', title=f'Race - {race.name}', racers=racers)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\race_info.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 117, in block 'content'
    {% block app_content %}{% endblock %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\race_info.html", line 9, in block 'app_content'
    <a href="{{ track.track_map}}" target="_blank"><img src="{{ track.track_map }}"></a>
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'track' is undefined
2021-10-17 19:32:41,158 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
