2021-11-17 05:14:59,607 ERROR: Exception on /achievements [GET] [in i:\anaconda\envs\cash\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "i:\anaconda\envs\cash\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\main\routes.py", line 1420, in achievements
    return render_template('achievements.html', completed_achievements=completed_achievements,
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\achievements.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 168, in block 'content'
    {% block app_content %}{% endblock %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\achievements.html", line 11, in block 'app_content'
    <h3>Achievement Points: {{ str(achievement_score) }}</h3>
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str' is undefined
2021-11-17 05:15:20,492 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:15:20,760 ERROR: Exception on /achievements [GET] [in i:\anaconda\envs\cash\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "i:\anaconda\envs\cash\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\main\routes.py", line 1420, in achievements
    return render_template('achievements.html', completed_achievements=completed_achievements,
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\achievements.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "i:\anaconda\envs\cash\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 168, in block 'content'
    {% block app_content %}{% endblock %}
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\achievements.html", line 11, in block 'app_content'
    <h3>Achievement Points: {{ str(achievement_score) }}</h3>
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str' is undefined
2021-11-17 05:15:34,300 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:45:03,831 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:46:27,671 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:47:17,033 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:47:32,177 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:59:48,714 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
2021-11-17 05:59:51,917 ERROR: Exception on /achievements [GET] [in i:\anaconda\envs\cash\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "i:\anaconda\envs\cash\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "i:\anaconda\envs\cash\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\main\routes.py", line 1420, in achievements
    return render_template('achievements.html', completed_achievements=completed_achievements,
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "i:\anaconda\envs\cash\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\achievements.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "i:\anaconda\envs\cash\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Evan\Documents\NewDayRP\cash-and-associates\app\templates\base.html", line 139, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-11-17 06:00:56,187 INFO: Cash & Associates startup [in E:\Evan\Documents\NewDayRP\cash-and-associates\app\__init__.py:74]
